# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Intel.PresentMon
PackageVersion: 1.10.0
PackageLocale: en-US
Publisher: Intel Corporation
PublisherUrl: https://www.intel.com/content/www/us/en/homepage.html
PrivacyUrl: https://www.intel.com/content/www/us/en/privacy/intel-privacy-notice.html
PackageName: Intel PresentMon
PackageUrl: https://github.com/GameTechDev/PresentMon
License: MIT License
ShortDescription: Capture and analyze the high-level performance characteristics of graphics applications on Windows.
Moniker: presentmon
Tags:
  - presentmon
Documentations:
  - DocumentLabel: README
    DocumentUrl: https://github.com/GameTechDev/PresentMon?tab=readme-ov-file#readme
ManifestType: defaultLocale
ManifestVersion: 1.6.0
